### ISSUE TITLE
Packagist usage

### ISSUE THREAD

**Issue by christophlehmann** [subhh/libconnect#12]
Hi, can you add the extension to packagist.org?

We use composer the typo3-ter composer repository is deprecated/cannot be used for some extensions

Steps are:

* Login in packagist.org with github credentials
* Add github project with your name(space) "sub/libconnect"
* Activate webhook (Github) to autoupdate the packagist project on new tags/branches

**Comment by christophlehmann** [comment]
Hi @percolatorWitt,

is there a chance to get composer usage?

**Comment by percolatorWitt** [comment]
I made a package [](https://packagist.org/packages/subhh/libconnect).

I changed the vendor name in the composer.js to subhh identical to github.
