### ISSUE TITLE
Exceptions due to service timeouts

### ISSUE THREAD

**Issue by christophlehmann** [subhh/libconnect#13]
In \Sub\Libconnect\Service\Request::Request you try to catch `GuzzleHttp\Exception\ServerException`, but it should be `\GuzzleHttp\Exception\ServerException`. 

Furthermore i would just catch `\Exception` because there are more which can occur, for example `\GuzzleHttp\Exception\ConnectException`

**Comment by christophlehmann** [comment]
Hi @percolatorWitt ,

Is there a chance to get it in master?

**Comment by percolatorWitt** [comment]
Hi,

zur Einfachheit mal kurz auf Deutsch. Sorry, das ging bei mir unter. Bin gerade in Elternzeit. Vielleicht ne komische Frage, aber wie merge ich jetzt deinen Code?

**Comment by christophlehmann** [comment]
Moin,

da müsste ein Button sein "Squash and Commit"
