### ISSUE TITLE
TYPO3 10.4 Compatibility

### ISSUE THREAD

**Issue by christophlehmann** [subhh/libconnect#15]
Hey, are there plans to make this extension compatible to TYPO3 10.4?

**Comment by percolatorWitt** [comment]
Hi, yes i want du make the extension compatible to TYPO3 10.4.

**Comment by christophlehmann** [comment]
I need it in the next weeks. Is it planned already? Do you need help? Is it sponsored already or can we share the sponsoring?

**Comment by percolatorWitt** [comment]
Hi,

I am in parental leave until 16th october. It was only sponsored for the first release for TYPO3 4.6. If you know what to do is for TYPO3 10.4 I am thankful for your help.

**Comment by christophlehmann** [comment]
Okay, we will do it. How would we do it in the future, can you give me privileges to this repository and solve #12 ?

We can also talk this, would you call me? 0431 53 00 60 -33
