### ISSUE TITLE
Task: Cleanup keys in f:translate ViewHelpers

### ISSUE THREAD

**Issue by christophlehmann** [subhh/libconnect#20]
Example: `<f:translate key="LLL:EXT:libconnect/Resources/Private/Language/locallang.xlf:tx_libconnect.ezb.miniform.searchform.headline" />`

It's not necessary to prefix the key with `LLL:EXT:libconnect/Resources/Private/Language/locallang.xlf`, because this file is the default location for translation labels

**Comment by percolatorWitt** [comment]
I removed  the prefixes.
